# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: text-perturbation 
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    braches: ["main"]
    paths-ignore:
      - 'README.md'

permissions:
   contents: read

  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-lastest, windows-lastest]
        python-version: ["3.9","3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version}}
      users: action/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest tox tox-gh-actions
        pip install -r requirements.txt
     - name: Test with tox
      run: tox

  

